### ISSUE TITLE
Confusing text in README

### ISSUE THREAD

**Issue by intrications** [johnkil/Print#10]
> First, you need to initialize the default iconic font in Application.onCreate() method. If the font is not specified, then the font is used by default.

I'm not sure what this means. Does this mean that if a font is not specified in the layout xml then this is the font that will be used?

Can the custom view be used without specifying the default font by always specifying it in the layout xml?

**Comment by johnkil** [comment]
Yes, it's default font, then it is used when a font is not specified.
