### ISSUE TITLE
UTF-16 Issue

### ISSUE THREAD

**Issue by bmelnychuk** [johnkil/Print#11]
I get "input is not valid Modified UTF-8: illegal start byte 0xf0" exception when i'm trying to use icon like &#x1f4de; I found similar problems it seems like parser issue. I have the solution for this can I make a pull request with changes?

**Comment by johnkil** [comment]
I can not reproduce this issue. How you got it in details?

**Comment by bmelnychuk** [comment]
Could you try this font https://www.dropbox.com/s/06ubv4w81vncbjh/SSStandard.zip?dl=0
This icon `&#x2709;  (.ss-mail)` works fine 
But this one `&#x1F4DE; (.ss-phone)` does not

Thanks

**Comment by johnkil** [comment]
Agree it is a problem, wait pull request :wink:

**Comment by johnkil** [comment]
@bmelnychuk Do I understand correctly: you have a solution to this problem?

**Comment by bmelnychuk** [comment]
Well, I have workaround rather, don't really like that. The idea is to use int resources instead of string. I will share it at weekend
