### ISSUE TITLE
Set icon color improvement.

### ISSUE THREAD

**Issue by korest** [johnkil/Print#13]
Could you please add one more method similar to "setIconColor" that takes just a simple color(but not resourse id) as argument.

**Comment by bmelnychuk** [comment]
What about backward compatibility here? With this fix my existing code will not work, as I used setColor(int) with resourceId, and now I have to rename setColor to setColorRes everywhere.

**Comment by johnkil** [comment]
@bmelnychuk I agree, it's not a very good decision. But it's my fault that I missed the ability to set the color (not using resource identifier). In any case, if you have a problem to migrate to the new API you can use the previous version of the library (1.2.3), the difference between the versions is negligible.
