### ISSUE TITLE
Issue with font icon alignment in action bar

### ISSUE THREAD

**Issue by SanthoshDhandapani** [johnkil/Print#8]
Hi johnkil, Thank you very much for such a amazing library. I used your library to make font icons in action bar and i ended up like this (Used font awesome ttf)

![action_bar](https://cloud.githubusercontent.com/assets/10140204/5501109/7681ff20-877a-11e4-99c8-4ab218e63583.jpeg)

I need my icons to be aligned in parallel with the setting icon which is on the right corner like an usual action bar. 

Please help me in achieving this.

**Comment by SanthoshDhandapani** [comment]
This fix is exact and so cool. Thank you very much.

**Comment by johnkil** [comment]
:blush:
